---
- hosts: all
  user: ec2-user
  sudo: true

  vars_files:
    - common_list.yaml
  tasks:
    - name: install packages from list
      yum: name={{ item }} state=installed
      loop: "{{  listOfPackages  }}"
